### PR TITLE
Run go mod vendor to update the vendorized dependencies

### PR DESCRIPTION
**Pull request by marcospereira**
Follow up to #55:

- Use the same go version as the project
- Also build the image for pull requests
- go mod vendor

### CODE REVIEW

**Comment by marcospereira** [comment]
yeah, yeah, those ridiculous numbers again: `+285,312 −4,516,038`.

**Comment by marcospereira** [comment]
Again merging it myself to validate the progress.

**Comment by marcospereira** [comment]
Good, good: https://github.com/lightbend/akka-cluster-operator/actions/runs/962078864

**Review by marcoderama — COMMENTED** [review]
lgtm

**Pull request merged**
