### PR TITLE
Merge certified in Master

### PR DESCRIPTION
**Pull request by edwardcallahan**
Seeking to bring the certified branch changes into master so that there can be one source of truth!

### CODE REVIEW

**Review by marcoderama — APPROVED** [review]
lgtm

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by lightbend-cla-validator** [comment]
At least one pull request committer is not linked to a user. See https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user

**Comment by edwardcallahan** [comment]
Now passing checks in https://github.com/operator-framework/community-operators/pull/847 and https://github.com/operator-framework/community-operators/pull/848

**Pull request merged**
