### PR TITLE
Replace Bintray with Lightbend registry

### PR DESCRIPTION
**Pull request by marcospereira**
- [x] Replace all bintray registry occurrences with Lightbend registry
- [x] Update Github secrets

### CODE REVIEW

**Review by andreaTP — APPROVED** [review]

**Review by RayRoestenburg — APPROVED** [review]

**Review by marcoderama — APPROVED** [review]
I presume the next PR will be for a new release of the operator?

**Comment by marcospereira** [comment]
> I presume the next PR will be for a new release of the operator?

I guess so. However, it is unclear to me how to do that. @marcoderama, are there any instructions about how to cut a release after the changes are complete?

**Comment by marcospereira** [comment]
I can see an image was pushed to registry.lightbend.com. 🎉

**Comment by marcoderama** [comment]
> > I presume the next PR will be for a new release of the operator?
> 
> I guess so. However, it is unclear to me how to do that. @marcoderama, are there any instructions about how to cut a release after the changes are complete?

I dunno.  @edwardcallahan ?

**Comment by marcospereira** [comment]
@jtownley I remember you mentioned someone would do the release, but I don't remember who. Now that this is merged, we can cut a new release.

**Comment by edwardcallahan** [comment]
I would expect that publishing a new release to operator hub will require updates to the operator-sdk, yaml, etc in order meet current criteria.

**Comment by jtownley** [comment]
Adding Adam

@Adam, can you assist with this? This is for the redhat marketplace.


--James

**Comment by marcospereira** [comment]
> I would expect that publishing a new release to operator hub will require updates to the operator-sdk, yaml, etc in order meet current criteria.

Thanks for chiming in, @edwardcallahan. Some follow up questions:

Do you know what is the required version for the operator? I'm not familiar with this project at all, but I can see we have multiple versions here and there. For example:

https://github.com/lightbend/akka-cluster-operator/blob/master/go.mod#L49

And:

https://github.com/lightbend/akka-cluster-operator/blob/master/.github/action/operator-sdk/Dockerfile#L12

Where can I see the current criteria for a new release?

**Comment by marcospereira** [comment]
@jtownley @chainlynx, is this where we are supposed to see the released operator?

https://operatorhub.io/operator/akka-cluster-operator

We have a [1.0.2 release](https://github.com/lightbend/akka-cluster-operator/releases/tag/v1.0.2) here in the repository, but it is not listed there. 🤔

**Comment by edwardcallahan** [comment]
@marcospereira Correct, it is the operatorhub.io bit we are missing. 
The operator-sdk doc site https://sdk.operatorframework.io/docs/  is the doc for that process.
Contribute on operatorhub is the entry point https://operatorhub.io/packages for new versions
Note that there is a `community-operators` AND a `upstream-community-operators` in https://github.com/operator-framework/community-operators. One is for OS and the other K8s.
For enterprise there is a different, private registry and process. A third packaging of the operator. Brad knows about that one.

**Pull request merged**
